# Generated by Django 6.0.4 on 2026-05-13 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kakeibo', '0002_alter_expense_memo'),
    ]

    operations = [
        migrations.CreateModel(
            name='FixedCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='固定費名')),
                ('amount', models.IntegerField(verbose_name='金額')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kakeibo.category', verbose_name='カテゴリ')),
            ],
            options={
                'verbose_name': '固定費',
                'verbose_name_plural': '固定費一覧',
            },
        ),
    ]
