# Generated by Django 6.0.4 on 2026-05-15 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kakeibo', '0003_fixedcost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='user',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='user',
        ),
    ]
