# Generated by Django 6.0.4 on 2026-05-15 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kakeibo', '0005_family_fixedcost_user_category_family_expense_family_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixedcost',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kakeibo.family'),
        ),
    ]
