# Generated by Django 6.0.4 on 2026-05-25 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kakeibo', '0006_alter_fixedcost_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='family',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='family',
        ),
        migrations.RemoveField(
            model_name='fixedcost',
            name='user',
        ),
    ]
