# Generated by Django 5.2.14 on 2026-06-18 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kakeibo', '0008_alter_category_id_alter_expense_id_alter_family_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialExpense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.IntegerField()),
                ('type', models.CharField(choices=[('summer_bonus', '夏ボ'), ('winter_bonus', '冬ボ'), ('travel', '旅行費'), ('other', 'その他')], max_length=20)),
                ('memo', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
