# Generated by Django 5.2.14 on 2026-06-28 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kakeibo', '0010_income'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='specialexpense',
            name='memo',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='specialexpense',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kakeibo.specialtype'),
        ),
    ]
