# Generated by Django 5.2.14 on 2026-06-28 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kakeibo', '0011_specialtype_alter_specialexpense_memo_and_more'),
    ]

    operations = [
    ]
