# Generated by Django 5.2.14 on 2026-07-21 13:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kakeibo', '0012_auto_20260628_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='fixed_cost',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='kakeibo.fixedcost', verbose_name='固定費'),
        ),
        migrations.AddField(
            model_name='fixedcost',
            name='day',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='支払日（毎月）'),
        ),
        migrations.AddField(
            model_name='fixedcost',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='有効'),
        ),
        migrations.AddField(
            model_name='fixedcost',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='開始月'),
        ),
    ]
