# Generated by Django 5.2.14 on 2026-07-21 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kakeibo', '0013_expense_fixed_cost_fixedcost_day_fixedcost_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixedcost',
            name='last_generated',
            field=models.DateField(blank=True, null=True, verbose_name='最終生成月'),
        ),
    ]
