# Generated by Django 5.2.14 on 2026-07-21 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kakeibo', '0014_fixedcost_last_generated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fixedcost',
            options={'verbose_name': '定額費', 'verbose_name_plural': '定額費一覧'},
        ),
        migrations.AlterField(
            model_name='expense',
            name='fixed_cost',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='kakeibo.fixedcost', verbose_name='定額費'),
        ),
        migrations.AlterField(
            model_name='fixedcost',
            name='name',
            field=models.CharField(max_length=100, verbose_name='定額費名'),
        ),
    ]
